version: '3.1'
services:
  app:
    container_name: stock-service
    image: stock-service-v1
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - dbpostgresql
    volumes:
      - ~/docker/stock:/stock-service/logs
  dbpostgresql:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres